namespace: ecuaalejo2013-dev
name: cmtx-api-public
image:
  repository: docker.io/alexisvg2520/cmtx-api-public
  tag: latest
resources:
  requests: { cpu: 30m, memory: 128Mi }
  limits:   { cpu: 200m, memory: 256Mi }
env:
  DATA_HOST: 172.30.29.175
  DATA_PORT: "8080"
