name: build-and-deploy
on: 
  push:
    branches: ["master"]
    paths:
      - 'chart/**'
      - '.github/workflows/build-deploy.yaml'
  workflow_dispatch: {}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build & push image
        run: |
          echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
          docker build -t docker.io/${{ secrets.DOCKERHUB_USERNAME }}/cmtx-api-public:${{ github.sha }} .
          docker push docker.io/${{ secrets.DOCKERHUB_USERNAME }}/cmtx-api-public:${{ github.sha }}
          docker tag docker.io/${{ secrets.DOCKERHUB_USERNAME }}/cmtx-api-public:${{ github.sha }} docker.io/${{ secrets.DOCKERHUB_USERNAME }}/cmtx-api-data:latest
          docker push docker.io/${{ secrets.DOCKERHUB_USERNAME }}/cmtx-api-public:latest
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Install OC CLI
        run: |
          curl -L https://mirror.openshift.com/pub/openshift-v4/clients/ocp/latest/openshift-client-linux.tar.gz | tar xz
          sudo mv oc /usr/local/bin/
          oc version
      - name: Install Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.12.0
      - uses: actions/checkout@v4
      - uses: redhat-actions/oc-login@v1
        with:
          openshift_server_url: ${{ secrets.OPENSHIFT_SERVER }}
          openshift_token:      ${{ secrets.OPENSHIFT_TOKEN }}
          insecure_skip_tls_verify: true
          namespace: ecuaalejo2013-dev
      - uses: azure/setup-helm@v4
      - name: Helm upgrade
        run: |
          helm upgrade --install cmtx-api-public chart -n ecuaalejo2013-dev \
            --set image.repository=docker.io/${{ secrets.DOCKERHUB_USERNAME }}/cmtx-api-public \
            --set image.tag=${{ github.sha }}